version: "3.9"

services:
  web:
    build: ./docker/nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  app:
    build: ./docker/php
    container_name: php
    ports:
      - "5173:5173"
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
  db:
    image: mysql:latest
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datadase
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/mysql/db:/var/lib/mysql
  mail:
    image: mailhog/mailhog:latest
    container_name: mail
    ports:
      - "8025:8025"
      - "1025:1025"
